### ISSUE TITLE
Service 'cron' failed to build: invalid reference format after fix #223

### ISSUE THREAD

**Issue by Hookibibi** [getsentry/onpremise#226]
Even after the fix released earlier, I still have the issue

` > ./install.sh 
Checking minimum requirements...

Creating volumes for persistent storage...
Created sentry-data.
Created sentry-postgres.

.env already exists, skipped creation.

Building and tagging Docker images...

WARNING: The IMAGE variable is not set. Defaulting to a blank string.
postgres uses an image, skipping
redis uses an image, skipping
smtp uses an image, skipping
memcached uses an image, skipping
Building cron
Step 1/2 : ARG IMAGE=sentry:9.1.2
Step 2/2 : FROM ${IMAGE}-onbuild
ERROR: Service 'cron' failed to build: invalid reference format
Cleaning up...
`

**Comment by lufrankland** [comment]
Just as a quick fix, I found adding 
`IMAGE=sentry:9.1.2`
to the **.env** will fix the issue. Obviously it needs a better default but it should get you going in the start

**Comment by BYK** [comment]
Should be fixed with #231. Sorry for the trouble :(

**Comment by BeCareOfZm** [comment]
the issue is still exist, it doesn't repair， now add `SENTRY_IMAGE=sentry:9.1.2` will fix the issue

**Comment by gaokun** [comment]
Yes, this issue is still there.
```
postgres uses an image, skipping
redis uses an image, skipping
smtp uses an image, skipping
memcached uses an image, skipping
Building cron
Step 1/2 : ARG SENTRY_IMAGE
Step 2/2 : FROM ${SENTRY_IMAGE}-onbuild
ERROR: Service 'cron' failed to build: invalid reference format 
```

after add `SENTRY_IMAGE=sentry:9.1.2` to `.env` file, it works.

```

Successfully built 0ad8c9efdaa3
Successfully tagged onpremise_cron:latest
Building worker
Step 1/2 : ARG SENTRY_IMAGE
Step 2/2 : FROM ${SENTRY_IMAGE}-onbuild
# Executing 4 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> 0ad8c9efdaa3

Successfully built 0ad8c9efdaa3
Successfully tagged onpremise_worker:latest
Building web
Step 1/2 : ARG SENTRY_IMAGE
Step 2/2 : FROM ${SENTRY_IMAGE}-onbuild
# Executing 4 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> 0ad8c9efdaa3

Successfully built 0ad8c9efdaa3
Successfully tagged onpremise_web:latest
```

**Comment by BYK** [comment]
Yes, you need to be using the `./install.sh` script or set `SENTRY_IMAGE=sentry:9.1.2` manually if you want to roll your own.

**Comment by uhlhosting** [comment]
This is a must to be noted in latest changes, where ARG IMAGE=$IMAGE was removed from .env file.

**Comment by BYK** [comment]
@uhlhosting I think https://github.com/getsentry/onpremise/pull/252/files addresses this now?
