### ISSUE TITLE
Restore following documentation fails

### ISSUE THREAD

**Issue by bretteville** [getsentry/onpremise#919]
I am trying to recover from an error where nothing is able to connect to kafka after upgrading from 21.2.0 to 21.3.0. After hitting my head in the brick wall for too long I decided to back up settings using the process described [here](https://develop.sentry.dev/self-hosted/backup/), do a clean install and restore. Backup works fine, restore on the other hand does not. It fails. I tried twice, the first time I did not create a user and rand "sudo docker-compose up -d" before the restore. The second time I created the initial user an ran the restore command directly without bringing Sentry up first. Does not seem to have any impact on the result. Output attached.

[t.txt](https://github.com/getsentry/onpremise/files/6264201/t.txt)

``

**Comment by bretteville** [comment]
Forgot to mention that before the re-install volumes were purged and a fresh new "onpremise" directory created to ensure nothing was left from the previous installs.

**Comment by BYK** [comment]
What is the version of Sentry you are trying to restore into?

**Comment by bretteville** [comment]
I am attempting to restore into 21.3.0, the same version that is causing me all the Kafka headache (not being able to communincate with Kafka seems rather poetic).

**Comment by BYK** [comment]
@bretteville I'll investigate the backup/restore issue but have you tried this for Kafka: https://develop.sentry.dev/self-hosted/troubleshooting/#kafka

**Comment by bretteville** [comment]
@BYK Yes, I tried that and it does not cahnge anything. The problem is in connecting to Kafka, though not dns related, I can curl Kafka fro the relay container and it resovled the correct IP. In the container logs I keep seeing sequences of these errors:

`2021-04-06T17:25:19Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.11:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-04-06T17:25:19Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#172.21.0.11:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)
2021-04-06T17:25:20Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 403 Forbidden
  caused by: no error details
`

**Comment by bretteville** [comment]
@BYK There is something specific in the backup.json file that caues the restore to fail. Is there any way to get the restore process to output what it is doing? Can't seem to find any way to enable debug logging.

**Comment by BYK** [comment]
@bretteville is it okay for you to share the `backup.json` file with a private gist or something so we can try locally? My email is my github username @ mycompany . io

**Comment by bretteville** [comment]
@BYK There is something specific in the backup.json file that caues the restore to fail. Is there any way to get the restore process to output what it is doing? Can't seem to find any way to enable debug logging.

> @bretteville is it okay for you to share the `backup.json` file with a private gist or something so we can try locally? My email is my github username @ mycompany . io

No need to make it hard. Here is a docktored json based on my initial backup that bombs out in excatly the same way during restore on a freshly installed system. I have removed all the user, team and project info as well as the gitlab integration settings.

To reproduce:
- Install 21.2.0
- Install 21.3.0
- docker-compose run -T web import /etc/sentry/boom.json

There are reports in the user community of people having issues getting clean installs of 21.3.0 to run. I had identical issues which were solved by installing 21.2.0 first. Hence the procedure above.

[boom.tar.gz](https://github.com/getsentry/onpremise/files/6297029/boom.tar.gz)

**Comment by BYK** [comment]
Hi @bretteville, sorry for the late response. I was able to get the file imported by removing the following two records:
```json
{
  "model": "sentry.organizationmemberteam",
  "pk": 1,
  "fields": {
    "team": 1,
    "organizationmember": 1,
    "is_active": true
  }
}
```

and 

```json
{
  "model": "sentry.team",
  "pk": 1,
  "fields": {
    "organization": 1,
    "slug": "sentry",
    "name": "Sentry",
    "status": 0,
    "actor": 10,
    "date_added": "2020-11-24T15:14:50.988Z"
  }
},
```

Not sure why the referred fields (`actor_id=10`) and (`organizationmember_id=1`) were missing from the export. Will investigate.

**Comment by bretteville** [comment]
Actor 10 is there in the unedited backup.json. I removed anything that was specific to the install. I will change email addresses and password hashes and email you a full backup.json. Saves you looking for issues where they are not.

**Comment by BYK** [comment]
>Actor 10 is there in the unedited backup.json. I removed anything that was specific to the install. I will change email addresses and password hashes and email you a full backup.json. Saves you looking for issues where they are not.

I'm not looking for issues, I'm trying to reproduce the issue you are experiencing. I've talked to @wedamija and he mentioned we added the actors model and constraints recently, which may explain the issue I had when trying to restore this backup onto a fresh 21.5.0.dev0 instance.

I am unable to reproduce the content-type related issues you mentioned in your original post. Could you try on the latest version (21.4.1 right now released yesterday) with those pieces removed and see if you still get the original error (or _any_ error)?

**Comment by bretteville** [comment]
Apologies for the choice of words, what I meant was that my removing parts of the backup may cause problems for the restore that. I have emailed you an anonymized full backup and will test 21.4.1

**Comment by bretteville** [comment]
Today's testing:
- Installed 21.4.1 on a clean system
Removed the two block and restore still fails. Trace attached.

On the content issue:
I can not get it to accept events in an environment that is similar to where we have it set up for the developers. It proxies http/https traffic through squid. I can follow them as far in as relay and then nothing. Adding sample events from the web-ui also fails. That is you get a message in the lower right saying "adding event" and then "failed to add". If you then go to look at events for the project it the system sees that it has one, but can't retreive it. All this is silent. No error messages in any logs that I can see. In a VM on a laptop outside the development environment that is not proxied I have no problems getting sample events to work so I fully accept that the proxied environment is likely the culprit, though I can find no documentation from Sentry on that use case. I can't believe we are the only needing Sentry to work in such an environment.


[restore-after-edit.txt](https://github.com/getsentry/onpremise/files/6363449/restore-after-edit.txt)

**Comment by bretteville** [comment]
Here is some further information on the content creation problem.

1: Install 21.2.0 on a clean docker node
2: log in and create a sample event in the sample project. This works, as expected
3: Take sentry down
4: copy files for 21.3.0 over the existing installation
5: run `install.sh `
6: save `.env`
7: run `scripts/bump_version.sh 21.2.0 21.3.0`
8: replace `.env` with copy (docker image names mangled by `bump_version.sh`)
9: bring sentry up
10: wait two minutes to ensure everything is up and nginx has sorted dns out
11: go to project page in web ui and create new (python) project
12: create sample event for new project. This works as expected
13 take sentry down
14: run 4 through 10 again, this time with 21.4.1 (or 21.4.0)
15: go to web ui and create a new project, ruby this time
16: create a sample event for the new project. This time it does not work

If I install 21.3.0 or 21.4.x directly creating sample events fail. Every time.

Clearly something has changed from 21.2.0 onwards. I had the system up and running from 20.10.1 adding each new release on top of the former.

**Comment by BYK** [comment]
I cannot understand why you are running steps 4 to 10. This also seems to be the root cause of your restore issues. Here's how you should proceed:

### To restore the backup on a fresh installation

1. Checkout the onpremise repo
2. Place your backup file under the `sentry` directory in this repo
3. Run `CI=1 ./install.sh` (this will skip the prompt for user creation)
4. Run `docker-compose run --rm -T web import /etc/sentry/<your_backup_file>.json`
5. Run `docker-compose up -d`
6. Profit

### To upgrade an existing installation

1. Run `git pull` inside your original onpremise checkout
2. Run `git checkout <version?`
3. Run `./install.sh`
4. Wait...
5. Run `docker-compose up -d`
6. Profit

**Comment by bretteville** [comment]
I have gone through a series of tests today, working as close as I can to what you suggest above. We operate behind a http(s) proxy so some overrides are required to make anything work. 

Installing 21.2.0 is painless. It builds and runs as expected. I start it in two stages to reduce the noise in the logs. First kafka, redis, memcached, postgres, clickhouse and web. Then the rest. Relay's log tells me it is able to register with upstream as expected. I go through the initial setup dialogue in the web UI. I can create a sample event from the and get a crash report submitted from a sample app as expected.

After this I take sentry down, check out 21.3.0, add the necessary overrides and run install.sh, images are downloaded and built. I bring Sentry up. Relay is not happy. It is not able to connect to upstream and throws 403 errors trying to connect to http://web:9000. If i `curl -vv http://web:9000` from within the relay container I get a 302 redirect as expected and the name resolution is clearly OK.
In the web UI I am able t create a new project and create a sample event from the web UI. When I run my test app again it reports no error while submitting the crash report. I can see it being received by Relay, but it does not appear in the web ui.

I have tried setting relay's log level to `trace` and I have tried to set Web's log level through the "SENTRY_LOG_LEVEL environment variable to "DEBUG", but I can't see any issues reported in Web's log output. 

In my environment this happens every time 100% reproducable. The same 403 problem appears if I start with 21.3.0 and skip 21.2.0.

**Comment by BYK** [comment]
@bretteville sorry for the lack of response here. Can I assume that the backup/restore issue was resolved and you had another issue with Relay?

**Comment by bretteville** [comment]
@BYK The restore problem was not resolved, but we were able to recreate the setup. Got the users and teams from the backup, though all projects had to be recreated.
With the release of 21.5.1 I have been successful in upgrading from 21.3.0 (upgraded from 21.2.0) as well as doing a clean install on my staging server. This is progress as 21.3.x did not run properly when a clean install was made, neither did 21.4.0/1. I have not upgraded the live server yet, but it seems that by skipping 21.4.x we are OK - for now at least.

**Comment by BYK** [comment]
@bretteville ah, gotcha. Thanks a lot for the detailed follow up.

So from what I understand:

1. We may still be unable to restore backups made with older versions
2. The export/import in 21.5+ works as expected (assumption)
3. The upgrade to `21.3` and `21.4` was not working for some reason but this is now fixed with `21.5`

Are these accurate?

**Comment by bretteville** [comment]
1. I was not able to restore to the same version, except for the part that held users. I have not tried export in 21.3.0 and import in 21.5.1, but I can do that.
2. Not tested, but will do that
3. upgrade from 21.2 to 21.3 works. Upgrade from 21.3 to 21.4 renders the system in a broken state. Upgrade from 21.3 to 21.5 works
4. Additionally: in my environment clean installs of 21.3 and 21.4 renders the systems broken. The only way for me to get to 21.3 is to upgrade 21.2. Clean install of 21.5 is OK. This is all in an environment that sits behind a squid proxy.
